// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD7p24QKAcWkW5VFXCGwf4H_qDe5Wt1WY',
    appId: '1:49296231033:web:9c3959542bce6205e1a2a8',
    messagingSenderId: '49296231033',
    projectId: 'flutter-practice-1-4fee8',
    authDomain: 'flutter-practice-1-4fee8.firebaseapp.com',
    storageBucket: 'flutter-practice-1-4fee8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbHtYXeB4raeSb6v3tqrBqAnDuCXFIfDQ',
    appId: '1:49296231033:android:705405543bb48aade1a2a8',
    messagingSenderId: '49296231033',
    projectId: 'flutter-practice-1-4fee8',
    storageBucket: 'flutter-practice-1-4fee8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_u51gMje9BX0dKfyxlVp9vy1up1IPaEw',
    appId: '1:49296231033:ios:4290a0f5031dba11e1a2a8',
    messagingSenderId: '49296231033',
    projectId: 'flutter-practice-1-4fee8',
    storageBucket: 'flutter-practice-1-4fee8.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

}